### ISSUE TITLE
Build with yocto for release/foxy failes

### ISSUE THREAD

**Issue by Betatester777** [ros2-gbp/rcl_logging-release#7]
Yocto release "Zeus"

Yocto build for arm rcl_logging_spdlog build cases an error

branch:
release/foxy/rcl_logging_spdlog

revision:  https://github.com/ros2-gbp/rcl_logging-release/commit/20f807606bcfea64746b9d11bd4009d631671a2b

`ERROR: rcl-logging-spdlog-1.0.0-1-r0 do_configure: Execution of '/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/temp/run.do_configure.589552' failed with exit code 1:
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
-- Check for working C compiler: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++
-- Check for working CXX compiler: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake_ros: 0.9.0 (/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/share/ament_cmake_ros/cmake)
-- Found PythonInterp: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.7.8", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/python3-native/python3
-- Found rcutils: 1.0.1 (/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/share/rcutils/cmake)
-- Found spdlog_vendor: 1.1.3 (/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/share/spdlog_vendor/cmake)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Findrcpputils.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "rcpputils", but CMake did not find one.

  Could not find a package configuration file provided by "rcpputils" with
  any of the following names:

    rcpputilsConfig.cmake
    rcpputils-config.cmake

  Add the installation prefix of "rcpputils" to CMAKE_PREFIX_PATH or set
  "rcpputils_DIR" to a directory containing one of the above files.  If
  "rcpputils" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/build/CMakeFiles/CMakeOutput.log".
See also "/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/build/CMakeFiles/CMakeError.log".
WARNING: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/temp/run.do_configure.589552:1 exit 1 from 'cmake -G 'Ninja' -DCMAKE_MAKE_PROGRAM=ninja $oecmake_sitefile /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/git -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=bin -DCMAKE_INSTALL_SBINDIR:PATH=sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_DATAROOTDIR:PATH=share -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/toolchain.cmake -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 -DBUILD_TESTING=OFF -DPYTHON_SOABI=cpython-37m-aarch64-linux-gnu -Wno-dev'

ERROR: Logfile of failure stored in: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/temp/log.do_configure.589552
`

Adding of rcpputil to ROS_BUILD_DEPENDS in rcl-logging-spdlog_1.0.0-1.bb makes an another error:

`DEBUG: Executing shell function do_compile
NOTE: VERBOSE=1 cmake --build /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/build --target all -- -j 8
[1/2] /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++  -DFMT_LOCALE -DFMT_SHARED -DRCL_LOGGING_BUILDING_DLL -DROS_PACKAGE_NAME=\"rcl_logging_spdlog\" -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -Drcl_logging_spdlog_EXPORTS -I/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/git/rcl_logging_spdlog/include -mcpu=cortex-a53+crc+crypto   --sysroot=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0=/usr/src/debug/rcl-logging-spdlog/1.0.0-1-r0                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0=/usr/src/debug/rcl-logging-spdlog/1.0.0-1-r0                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -mcpu=cortex-a53+crc+crypto   --sysroot=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot -fPIC   -Wall -Wextra -Wpedantic -std=gnu++14 -MD -MT CMakeFiles/rcl_logging_spdlog.dir/src/rcl_logging_spdlog.cpp.o -MF CMakeFiles/rcl_logging_spdlog.dir/src/rcl_logging_spdlog.cpp.o.d -o CMakeFiles/rcl_logging_spdlog.dir/src/rcl_logging_spdlog.cpp.o -c /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/git/rcl_logging_spdlog/src/rcl_logging_spdlog.cpp
[2/2] : && /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ -fPIC -mcpu=cortex-a53+crc+crypto   --sysroot=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0=/usr/src/debug/rcl-logging-spdlog/1.0.0-1-r0                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0=/usr/src/debug/rcl-logging-spdlog/1.0.0-1-r0                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -mcpu=cortex-a53+crc+crypto   --sysroot=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -shared -Wl,-soname,librcl_logging_spdlog.so -o librcl_logging_spdlog.so CMakeFiles/rcl_logging_spdlog.dir/src/rcl_logging_spdlog.cpp.o  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/librcpputils.so  -lpthread  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libfmt.so.8.1.1  -Wl,--as-needed  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/librcutils.so  -ldl && :
FAILED: librcl_logging_spdlog.so 
: && /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ -fPIC -mcpu=cortex-a53+crc+crypto   --sysroot=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0=/usr/src/debug/rcl-logging-spdlog/1.0.0-1-r0                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0=/usr/src/debug/rcl-logging-spdlog/1.0.0-1-r0                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden  -mcpu=cortex-a53+crc+crypto   --sysroot=/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot  -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -shared -Wl,-soname,librcl_logging_spdlog.so -o librcl_logging_spdlog.so CMakeFiles/rcl_logging_spdlog.dir/src/rcl_logging_spdlog.cpp.o  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/librcpputils.so  -lpthread  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libfmt.so.8.1.1  -Wl,--as-needed  /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/librcutils.so  -ldl && :
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN6spdlog9spdlog_exE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `spdlog::spdlog_ex::spdlog_ex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/usr/src/debug/spdlog/1.10.0-r0/git/include/spdlog/common-inl.h:53:(.text+0x1a8): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `void std::_Destroy_aux<false>::__destroy<spdlog::details::log_msg_buffer*>(spdlog::details::log_msg_buffer*, spdlog::details::log_msg_buffer*)':
/usr/include/c++/9.2.0/bits/stl_construct.h:107:(.text+0x2c8): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/include/c++/9.2.0/bits/stl_construct.h:107:(.text+0x3f4): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `__gnu_cxx::new_allocator<spdlog::details::log_msg_buffer>::allocate(unsigned long, void const*)':
/usr/include/c++/9.2.0/ext/new_allocator.h:114:(.text+0x4d8): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `spdlog::details::circular_q<spdlog::details::log_msg_buffer>::copy_moveable(spdlog::details::circular_q<spdlog::details::log_msg_buffer>&&)':
/usr/src/debug/spdlog/1.10.0-r0/git/include/spdlog/details/circular_q.h:129:(.text+0x530): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >::basic_memory_buffer(fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >&&)':
/usr/include/fmt/format.h:739:(.text+0x153c): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN6spdlog6loggerE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `spdlog::logger::logger(spdlog::logger&&)':
/usr/src/debug/spdlog/1.10.0-r0/git/include/spdlog/logger-inl.h:33:(.text+0x1738): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >::basic_memory_buffer(std::allocator<char> const&)':
/usr/include/fmt/format.h:699:(.text+0x2060): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >::~basic_memory_buffer()':
/usr/include/fmt/format.h:705:(.text+0x2158): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN3fmt2v819basic_memory_bufferIcLm250ESaIcEEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `fmt::v8::basic_memory_buffer<char, 250ul, std::allocator<char> >::basic_memory_buffer(std::allocator<char> const&)':
/usr/include/fmt/format.h:699:(.text+0x2290): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN6spdlog17pattern_formatterE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `spdlog::pattern_formatter::pattern_formatter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, spdlog::pattern_time_type, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unordered_map<char, std::unique_ptr<spdlog::custom_flag_formatter, std::default_delete<spdlog::custom_flag_formatter> >, std::hash<char>, std::equal_to<char>, std::allocator<std::pair<char const, std::unique_ptr<spdlog::custom_flag_formatter, std::default_delete<spdlog::custom_flag_formatter> > > > >)':
/usr/src/debug/spdlog/1.10.0-r0/git/include/spdlog/pattern_formatter-inl.h:1029:(.text+0x3040): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux/../../libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/9.2.0/ld: /home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN6spdlog9spdlog_exE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot/usr/lib/libspdlog.a(spdlog.cpp.o): in function `spdlog::spdlog_ex::spdlog_ex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/usr/src/debug/spdlog/1.10.0-r0/git/include/spdlog/common-inl.h:56:(.text+0x35b4): dangerous relocation: unsupported relocation
/home/some-dev/workspace/builddir/tmp/work/aarch64-poky-linux/rcl-logging-spdlog/1.0.0-1-r0/recipe-sysroot-....`

**Comment by clalancette** [comment]
This is the release repository for rcl_logging; no source code is hosted here.

Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
